name: Cypress tests

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2 

      - name: Cypress tests
        uses: cypress-io/github-action@v6.5.0
        with:
          working-directory: buildBoxOne
          install-command: npm install
          build: npm run build
          start: npm start
