name: Cypress tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2 

      - name: Cypress tests
        uses: cypress-io/github-action@v6.5.0
        with:
          command: npx run cypress
